# Generated by Django 4.2.6 on 2023-10-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgattery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGattery',
            new_name='ProductGallery',
        ),
    ]
